CPP=g++
CPPFLAGS=-Wall -Iinc

OBJECTS=\
	src\Errors.o

HEADERS=\
	inc\Errors.h \
	inc\ErrorTypes.h \

TESTS=\

GTEST_DIR=C:\gtest-1.7.0\gtest-1.7.0

src\Errors.o: src\Errors.cpp $(HEADERS)
	$(CPP) -c src\Errors.cpp

	
	